// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 62fk78rY9xoShC3bnaKgA9
// Component: -WLyt8cvAaz

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  usePlasmicDataConfig,
  executePlasmicDataOp,
  usePlasmicDataOp
} from "@plasmicapp/react-web/lib/data-sources";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { PlasmicHead } from "@plasmicapp/react-web"; // plasmic-import: WXwVC2oLrrOI3/codeComponent
import { Embed } from "@plasmicpkgs/plasmic-basic-components"; // plasmic-import: PKldDYkH42/codeComponent
import Slider from "react-slick"; // plasmic-import: HOQUyOpClJ/codeComponent
import { Reveal } from "@plasmicpkgs/react-awesome-reveal"; // plasmic-import: R6s1FdhksG/codeComponent
import YouTube from "@plasmicpkgs/react-youtube"; // plasmic-import: CHO21V9uYw/codeComponent
import { Iframe } from "@plasmicpkgs/plasmic-basic-components"; // plasmic-import: CMDBvOhaI4s/codeComponent
import Button from "../../Button"; // plasmic-import: 02HmyteR4qq/component
import WhatsappButton from "../../WhatsappButton"; // plasmic-import: -w4zVRfnGC/component
import { AntdModal } from "@plasmicpkgs/antd5/skinny/registerModal"; // plasmic-import: xx93QbkHH5i/codeComponent
import ImagePreview from "../../ImagePreview"; // plasmic-import: 01XWUA7Wd5/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources"; // plasmic-import: lP7-syqRi0Vod/codeComponent

import { useScreenVariants as useScreenVariants_7YtAkblAUxFb } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 7Yt-akblAUxFb/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_bentuk_cintav_2.module.css"; // plasmic-import: 62fk78rY9xoShC3bnaKgA9/projectcss
import sty from "./PlasmicTemplate3.module.css"; // plasmic-import: -WLyt8cvAaz/css

import LocationPinSvgrepoComsvgIcon from "./icons/PlasmicIcon__LocationPinSvgrepoComsvg"; // plasmic-import: MNB752PXfu/icon
import CalendarCheckSvgrepoComsvgIcon from "./icons/PlasmicIcon__CalendarCheckSvgrepoComsvg"; // plasmic-import: -IsdiWPjUL/icon
import ClockSvgrepoCom1SvgIcon from "./icons/PlasmicIcon__ClockSvgrepoCom1Svg"; // plasmic-import: GDHEOglvzt/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: 2oSyQCFheDJ/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: XBieVn7nEqJ/icon
import WhatsappSvgrepoComsvgIcon from "./icons/PlasmicIcon__WhatsappSvgrepoComsvg"; // plasmic-import: 8wYuQ9ltP1/icon
import WashingHandsSvgrepoComsvgIcon from "./icons/PlasmicIcon__WashingHandsSvgrepoComsvg"; // plasmic-import: cM9KKnXrjB/icon
import Mask2SvgrepoComsvgIcon from "./icons/PlasmicIcon__Mask2SvgrepoComsvg"; // plasmic-import: ioPnHlLgy4/icon
import SocialDistancingSvgrepoComsvgIcon from "./icons/PlasmicIcon__SocialDistancingSvgrepoComsvg"; // plasmic-import: DcuxjPu_O-/icon
import CloseCircleSvgrepoComsvgIcon from "./icons/PlasmicIcon__CloseCircleSvgrepoComsvg"; // plasmic-import: LT2cH1PbKL/icon

export type PlasmicTemplate3__VariantMembers = {};
export type PlasmicTemplate3__VariantsArgs = {};
type VariantPropType = keyof PlasmicTemplate3__VariantsArgs;
export const PlasmicTemplate3__VariantProps = new Array<VariantPropType>();

export type PlasmicTemplate3__ArgsType = {
  previewPopup?: boolean;
  onPreviewPopupChange?: (val: boolean) => void;
  clickedImgUrl?: string;
  onClickedImgUrlChange?: (val: string) => void;
};
type ArgPropType = keyof PlasmicTemplate3__ArgsType;
export const PlasmicTemplate3__ArgProps = new Array<ArgPropType>(
  "previewPopup",
  "onPreviewPopupChange",
  "clickedImgUrl",
  "onClickedImgUrlChange"
);

export type PlasmicTemplate3__OverridesType = {
  root?: p.Flex<"div">;
  pageMetadataOverride?: p.Flex<typeof PlasmicHead>;
  hero?: p.Flex<"div">;
  slider?: p.Flex<typeof Slider>;
  desc?: p.Flex<"div">;
  details?: p.Flex<"div">;
  contentWrapper?: p.Flex<"div">;
  title?: p.Flex<"div">;
  pengantinDetails?: p.Flex<"div">;
  man?: p.Flex<"div">;
  girl?: p.Flex<"div">;
  acaraDetails?: p.Flex<"div">;
  dateTime?: p.Flex<"div">;
  title5?: p.Flex<"div">;
  gallery?: p.Flex<"div">;
  contentWrapper2?: p.Flex<"div">;
  title2?: p.Flex<"div">;
  youTube?: p.Flex<typeof YouTube>;
  map?: p.Flex<"div">;
  contentWrapper3?: p.Flex<"div">;
  title3?: p.Flex<"div">;
  iframe?: p.Flex<typeof Iframe>;
  footer?: p.Flex<"div">;
  whatsappButton?: p.Flex<typeof WhatsappButton>;
  link?: p.Flex<"a"> & Partial<LinkProps>;
  modalTemplate3?: p.Flex<typeof AntdModal>;
  part1?: p.Flex<"div">;
  part12?: p.Flex<"div">;
  part13?: p.Flex<"div">;
  imagePreview?: p.Flex<typeof ImagePreview>;
};

export interface DefaultTemplate3Props {
  previewPopup?: boolean;
  onPreviewPopupChange?: (val: boolean) => void;
  clickedImgUrl?: string;
  onClickedImgUrlChange?: (val: string) => void;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicTemplate3__RenderFunc(props: {
  variants: PlasmicTemplate3__VariantsArgs;
  args: PlasmicTemplate3__ArgsType;
  overrides: PlasmicTemplate3__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const __nextRouter = useNextRouter();

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const stateSpecs = React.useMemo(
    () => [
      {
        path: "previewPopup",
        type: "writable",
        variableType: "boolean",

        valueProp: "previewPopup",
        onChangeProp: "onPreviewPopupChange"
      },
      {
        path: "clickedImgUrl",
        type: "writable",
        variableType: "text",

        valueProp: "clickedImgUrl",
        onChangeProp: "onClickedImgUrlChange"
      },
      {
        path: "modalTemplate3.open",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => true
      }
    ],
    [$props, $ctx]
  );
  const $state = p.useDollarState(stateSpecs, { $props, $ctx, $queries });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_7YtAkblAUxFb()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <PlasmicHead
        data-plasmic-name={"pageMetadataOverride"}
        data-plasmic-override={overrides.pageMetadataOverride}
        className={classNames("__wab_instance", sty.pageMetadataOverride)}
        description={"Undangan Online BentukCinta.com" as const}
        image={(() => {
          try {
            return $ctx.graphCmsItem.openGraphImage;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
        title={(() => {
          try {
            return "Bentuk Cinta | " + $ctx.graphCmsItem.title;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return undefined;
            }
            throw e;
          }
        })()}
      />

      {true ? (
        <Embed
          className={classNames("__wab_instance", sty.embedHtml__bxI4)}
          code={
            'import "slick-carousel/slick/slick.css";\nimport "slick-carousel/slick/slick-theme.css";' as const
          }
        />
      ) : null}
      <div
        data-plasmic-name={"hero"}
        data-plasmic-override={overrides.hero}
        className={classNames(projectcss.all, sty.hero)}
      >
        <Slider
          data-plasmic-name={"slider"}
          data-plasmic-override={overrides.slider}
          autoplay={true}
          autoplaySpeed={6000 as const}
          className={classNames("__wab_instance", sty.slider)}
        >
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__gp0Q5)}
            displayHeight={"auto" as const}
            displayMaxHeight={"none" as const}
            displayMaxWidth={"100%" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={"auto" as const}
            src={(() => {
              try {
                return $ctx.graphCmsItem.slideshows[0].slideImageUrl;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "https://via.placeholder.com/150x90/FF0000/FFFFFF/?text=Slide_1";
                }
                throw e;
              }
            })()}
          />

          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__qoO6)}
            displayHeight={"auto" as const}
            displayMaxHeight={"none" as const}
            displayMaxWidth={"100%" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={"auto" as const}
            src={(() => {
              try {
                return $ctx.graphCmsItem.slideshows[1].slideImageUrl;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "https://via.placeholder.com/150x90/00FF00/FFFFFF/?text=Slide_2";
                }
                throw e;
              }
            })()}
          />

          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__jAtSl)}
            displayHeight={"auto" as const}
            displayMaxHeight={"none" as const}
            displayMaxWidth={"100%" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={"auto" as const}
            src={(() => {
              try {
                return $ctx.graphCmsItem.slideshows[2].slideImageUrl;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "https://via.placeholder.com/150x90/0000FF/FFFFFF/?text=Slide_3";
                }
                throw e;
              }
            })()}
          />
        </Slider>
        <Reveal
          className={classNames("__wab_instance", sty.reveal__f8Xrl)}
          direction={"up" as const}
          triggerOnce={true}
        >
          <p.Stack
            as={"div"}
            data-plasmic-name={"desc"}
            data-plasmic-override={overrides.desc}
            hasGap={true}
            className={classNames(projectcss.all, sty.desc)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__tN7Fd
              )}
            >
              {"UNDANGAN PERNIKAHAN"}
            </div>
            <h2
              className={classNames(
                projectcss.all,
                projectcss.h2,
                projectcss.__wab_text,
                sty.h2__dc6Gb
              )}
            >
              <React.Fragment>
                {(() => {
                  try {
                    return $ctx.graphCmsItem.title;
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return "Jonh & Merry";
                    }
                    throw e;
                  }
                })()}
              </React.Fragment>
            </h2>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__d4Mnm
              )}
            >
              {
                "WE INVITE YOU TO CELEBRATE\nWITH US THE MOST SPECIAL DAY IN OUR LIFES"
              }
            </div>
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__vFqWh)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vyIVp
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return $ctx.graphCmsItem.evenDateTime.slice(5, 7) == 1
                          ? "Jan"
                          : $ctx.graphCmsItem.evenDateTime.slice(5, 7) == 2
                          ? "Feb"
                          : $ctx.graphCmsItem.evenDateTime.slice(5, 7) == 3
                          ? "Mar"
                          : $ctx.graphCmsItem.evenDateTime.slice(5, 7) == 4
                          ? "Apr"
                          : $ctx.graphCmsItem.evenDateTime.slice(5, 7) == 5
                          ? "May"
                          : $ctx.graphCmsItem.evenDateTime.slice(5, 7) == 6
                          ? "Jun"
                          : $ctx.graphCmsItem.evenDateTime.slice(5, 7) == 7
                          ? "Jul"
                          : $ctx.graphCmsItem.evenDateTime.slice(5, 7) == 8
                          ? "Aug"
                          : $ctx.graphCmsItem.evenDateTime.slice(5, 7) == 9
                          ? "Sep"
                          : $ctx.graphCmsItem.evenDateTime.slice(5, 7) == 10
                          ? "Oct"
                          : $ctx.graphCmsItem.evenDateTime.slice(5, 7) == 11
                          ? "Nov"
                          : "Dec";
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "Jan";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__c20R
                  )}
                >
                  {"●"}
                </div>
                <h5
                  className={classNames(
                    projectcss.all,
                    projectcss.h5,
                    projectcss.__wab_text,
                    sty.h5__hhWtX
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return $ctx.graphCmsItem.evenDateTime.slice(8, 10);
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "30";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </h5>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ynRz3
                  )}
                >
                  {"●"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__b4C7
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return $ctx.graphCmsItem.evenDateTime.slice(0, 4);
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "2023";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
              </p.Stack>
            ) : null}
          </p.Stack>
        </Reveal>
      </div>
      <div
        data-plasmic-name={"details"}
        data-plasmic-override={overrides.details}
        className={classNames(projectcss.all, sty.details)}
      >
        <p.Stack
          as={"div"}
          data-plasmic-name={"contentWrapper"}
          data-plasmic-override={overrides.contentWrapper}
          hasGap={true}
          className={classNames(projectcss.all, sty.contentWrapper)}
        >
          <Reveal
            className={classNames("__wab_instance", sty.reveal__jvz6D)}
            direction={"up" as const}
            triggerOnce={true}
          >
            {true ? (
              <p.Stack
                as={"div"}
                data-plasmic-name={"title"}
                data-plasmic-override={overrides.title}
                hasGap={true}
                className={classNames(projectcss.all, sty.title)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2___2TKCo
                  )}
                >
                  {"Om Swastiastu"}
                </h2>
                <h5
                  className={classNames(
                    projectcss.all,
                    projectcss.h5,
                    projectcss.__wab_text,
                    sty.h5__ktQ0
                  )}
                >
                  {"Mohon Doa Restu"}
                </h5>
              </p.Stack>
            ) : null}
          </Reveal>
          <p.Stack
            as={"div"}
            data-plasmic-name={"pengantinDetails"}
            data-plasmic-override={overrides.pengantinDetails}
            hasGap={true}
            className={classNames(projectcss.all, sty.pengantinDetails)}
          >
            <div className={classNames(projectcss.all, sty.column__wu0IW)}>
              <Reveal
                className={classNames("__wab_instance", sty.reveal___2Al0X)}
                direction={"up" as const}
                triggerOnce={true}
              >
                {true ? (
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"man"}
                    data-plasmic-override={overrides.man}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.man)}
                  >
                    {(() => {
                      try {
                        return $ctx.graphCmsItem.photoPria != null;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return false;
                        }
                        throw e;
                      }
                    })() ? (
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__lNWjM)}
                        displayHeight={"200px" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"200px" as const}
                        loading={"lazy" as const}
                        src={(() => {
                          try {
                            return $ctx.graphCmsItem.photoPria;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()}
                      />
                    ) : null}
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__um5Tm
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return $ctx.graphCmsItem.pengantinPria;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "Jonh Doe";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zC28C
                      )}
                    >
                      {"Putra dari pasangan"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mN3ZY
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return (
                              $ctx.graphCmsItem.bapakPria +
                              " & " +
                              $ctx.graphCmsItem.ibuPria
                            );
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "Rocky Doe & Jane Doe";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </div>
                    {true ? (
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ptPm3
                        )}
                      >
                        <LocationPinSvgrepoComsvgIcon
                          className={classNames(projectcss.all, sty.svg__lZc1H)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fbfd2
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $ctx.graphCmsItem.alamatPria;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "This is Bride Hometown Addess";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </p.Stack>
                    ) : null}
                  </p.Stack>
                ) : null}
              </Reveal>
            </div>
            <div className={classNames(projectcss.all, sty.column__u0Te)}>
              <Reveal
                className={classNames("__wab_instance", sty.reveal__g8H0Y)}
                delay={1 as const}
                direction={"up" as const}
                triggerOnce={true}
              >
                {true ? (
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"girl"}
                    data-plasmic-override={overrides.girl}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.girl)}
                  >
                    {(() => {
                      try {
                        return $ctx.graphCmsItem.photoWanita != null;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return false;
                        }
                        throw e;
                      }
                    })() ? (
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__pTkre)}
                        displayHeight={"200px" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"200px" as const}
                        loading={"lazy" as const}
                        src={(() => {
                          try {
                            return $ctx.graphCmsItem.photoWanita;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()}
                      />
                    ) : null}
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__iFuvo
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return $ctx.graphCmsItem.pengantinWanita;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "Merry Doe";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zwBbd
                      )}
                    >
                      {"Putra dari pasangan"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gOi
                      )}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return (
                              $ctx.graphCmsItem.bapakWanita +
                              " & " +
                              $ctx.graphCmsItem.ibuWanita
                            );
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "Rocky Doe & Jane Doe";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </div>
                    {true ? (
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__qlg9X
                        )}
                      >
                        <LocationPinSvgrepoComsvgIcon
                          className={classNames(projectcss.all, sty.svg__o1S2F)}
                          role={"img"}
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ykkky
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $ctx.graphCmsItem.alamatWanita;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "This is Bride Hometown Addess";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </p.Stack>
                    ) : null}
                  </p.Stack>
                ) : null}
              </Reveal>
            </div>
          </p.Stack>
          <Reveal
            className={classNames("__wab_instance", sty.reveal__al0Ro)}
            direction={"up" as const}
            triggerOnce={true}
          >
            {true ? (
              <p.Stack
                as={"div"}
                data-plasmic-name={"acaraDetails"}
                data-plasmic-override={overrides.acaraDetails}
                hasGap={true}
                className={classNames(projectcss.all, sty.acaraDetails)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__h0GYq)}
                  displayHeight={"102%" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100%" as const}
                  loading={"lazy" as const}
                  src={(() => {
                    try {
                      return $ctx.graphCmsItem.slideshows[0].slideImageUrl;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return undefined;
                      }
                      throw e;
                    }
                  })()}
                />

                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__rpUny)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ikp8O
                      )}
                    >
                      {
                        "Atas Asung Kertha Wara Nugraha Ida Sang Hyang Widhi Wasa/Tuhan Yang Maha Esa kami bermaksud mengundang Bapak/Ibu/Saudara/i pada Upacara Manusa Yadnya Pawiwahan (Pernikahan) Putra dan Putri kami"
                      }
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mAfpc
                      )}
                    >
                      {
                        "Merupakan suatu kehormatan dan kebahagiaan bagi kami, apabila Bapak / Ibu / Saudara / i berkenan hadir untuk memberikan doa restu, pada:"
                      }
                    </div>
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"dateTime"}
                      data-plasmic-override={overrides.dateTime}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.dateTime)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__vyw4R
                        )}
                      >
                        {true ? (
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__zxJxQ
                            )}
                          >
                            <CalendarCheckSvgrepoComsvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__uermj
                              )}
                              role={"img"}
                            />

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__inEqG
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return $ctx.graphCmsItem.evenDateTime.slice(
                                      8,
                                      10
                                    );
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "30";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__j3EtH
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return $ctx.graphCmsItem.evenDateTime.slice(
                                      5,
                                      7
                                    ) == 1
                                      ? "Jan"
                                      : $ctx.graphCmsItem.evenDateTime.slice(
                                          5,
                                          7
                                        ) == 2
                                      ? "Feb"
                                      : $ctx.graphCmsItem.evenDateTime.slice(
                                          5,
                                          7
                                        ) == 3
                                      ? "Mar"
                                      : $ctx.graphCmsItem.evenDateTime.slice(
                                          5,
                                          7
                                        ) == 4
                                      ? "Apr"
                                      : $ctx.graphCmsItem.evenDateTime.slice(
                                          5,
                                          7
                                        ) == 5
                                      ? "May"
                                      : $ctx.graphCmsItem.evenDateTime.slice(
                                          5,
                                          7
                                        ) == 6
                                      ? "Jun"
                                      : $ctx.graphCmsItem.evenDateTime.slice(
                                          5,
                                          7
                                        ) == 7
                                      ? "Jul"
                                      : $ctx.graphCmsItem.evenDateTime.slice(
                                          5,
                                          7
                                        ) == 8
                                      ? "Aug"
                                      : $ctx.graphCmsItem.evenDateTime.slice(
                                          5,
                                          7
                                        ) == 9
                                      ? "Sep"
                                      : $ctx.graphCmsItem.evenDateTime.slice(
                                          5,
                                          7
                                        ) == 10
                                      ? "Oct"
                                      : $ctx.graphCmsItem.evenDateTime.slice(
                                          5,
                                          7
                                        ) == 11
                                      ? "Nov"
                                      : "Dec";
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "Jan";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___7MfdD
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return $ctx.graphCmsItem.evenDateTime.slice(
                                      0,
                                      4
                                    );
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "2023";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                          </p.Stack>
                        ) : null}
                        {true ? (
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__sum2K
                            )}
                          >
                            <ClockSvgrepoCom1SvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__cUfKa
                              )}
                              role={"img"}
                            />

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__hJmQx
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return (
                                      $ctx.graphCmsItem.evenDateTime.slice(
                                        11,
                                        16
                                      ) + " s/d Selesai"
                                    );
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "05:00 s/d Selesai";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                          </p.Stack>
                        ) : null}
                        {true ? (
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__fraub
                            )}
                          >
                            <LocationPinSvgrepoComsvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__bgzp
                              )}
                              role={"img"}
                            />

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__icRbW
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return $ctx.graphCmsItem.eventLocation;
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "Event Address Location is Here";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                          </p.Stack>
                        ) : null}
                      </p.Stack>
                    </p.Stack>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hhXtF
                      )}
                    >
                      {
                        "Atas Kehadiran serta doa dan restu Bapak / Ibu / Saudara / i, kami ucapkan terima kasih"
                      }
                    </div>
                  </p.Stack>
                ) : null}
              </p.Stack>
            ) : null}
          </Reveal>
          <Reveal
            className={classNames("__wab_instance", sty.reveal__vc8PA)}
            direction={"up" as const}
            triggerOnce={true}
          >
            {true ? (
              <p.Stack
                as={"div"}
                data-plasmic-name={"title5"}
                data-plasmic-override={overrides.title5}
                hasGap={true}
                className={classNames(projectcss.all, sty.title5)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__g7Gs1
                  )}
                >
                  {"Om Shanti Shanti Shanti Om"}
                </h2>
              </p.Stack>
            ) : null}
          </Reveal>
        </p.Stack>
      </div>
      <div
        data-plasmic-name={"gallery"}
        data-plasmic-override={overrides.gallery}
        className={classNames(projectcss.all, sty.gallery)}
      >
        <p.Stack
          as={"div"}
          data-plasmic-name={"contentWrapper2"}
          data-plasmic-override={overrides.contentWrapper2}
          hasGap={true}
          className={classNames(projectcss.all, sty.contentWrapper2)}
        >
          <Reveal
            className={classNames("__wab_instance", sty.reveal__em1Xm)}
            triggerOnce={true}
          >
            {true ? (
              <p.Stack
                as={"div"}
                data-plasmic-name={"title2"}
                data-plasmic-override={overrides.title2}
                hasGap={true}
                className={classNames(projectcss.all, sty.title2)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__yqo5V
                  )}
                >
                  {"Gallery"}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bz9Ex
                  )}
                >
                  {
                    '"Ya Tuhanku yang Maha Pengasih, anugerahkanlah kepada pasangan pengantin ini senantiasa berbahagia keduanya tiada terpisahkan, panjang umur, semoga pengantin ini dianugerahkan putra dan cucu yang memberikan penghiburan, tinggal dirumah yang penuh kebahagiaan.”'
                  }
                </div>
              </p.Stack>
            ) : null}
          </Reveal>
          {(() => {
            try {
              return $ctx.graphCmsItem.youtubeUrl != null;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <YouTube
              data-plasmic-name={"youTube"}
              data-plasmic-override={overrides.youTube}
              className={classNames("__wab_instance", sty.youTube)}
              videoId={(() => {
                try {
                  return $ctx.graphCmsItem.youtubeUrl;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "R6MeLqRQzYw";
                  }
                  throw e;
                }
              })()}
            />
          ) : null}
          <div className={classNames(projectcss.all, sty.freeBox__lpvkh)}>
            {(
              (() => {
                try {
                  return $ctx.graphCmsItem.galleries;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return [];
                  }
                  throw e;
                }
              })() ?? []
            ).map((currentItem, currentIndex) => (
              <div
                className={classNames(projectcss.all, sty.freeBox___1PPe3)}
                key={currentIndex}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__iNcL)}
                  displayHeight={"300px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"300px" as const}
                  loading={"lazy" as const}
                  onClick={async event => {
                    const $steps = {};
                    $steps["updatePreviewPopup"] = true
                      ? (() => {
                          const actionArgs = {
                            variable: __wrapUserFunction(
                              {
                                type: "InteractionArgLoc",
                                actionName: "updateVariable",
                                interactionUuid: "feXYuzfq3LQ",
                                componentUuid: "-WLyt8cvAaz",
                                argName: "variable"
                              },
                              () => ({
                                objRoot: $state,
                                variablePath: ["previewPopup"]
                              })
                            ),
                            operation: __wrapUserFunction(
                              {
                                type: "InteractionArgLoc",
                                actionName: "updateVariable",
                                interactionUuid: "feXYuzfq3LQ",
                                componentUuid: "-WLyt8cvAaz",
                                argName: "operation"
                              },
                              () => 4
                            )
                          };
                          return __wrapUserFunction(
                            {
                              type: "InteractionLoc",
                              actionName: "updateVariable",
                              interactionUuid: "feXYuzfq3LQ",
                              componentUuid: "-WLyt8cvAaz"
                            },
                            () =>
                              (({
                                variable,
                                value,
                                startIndex,
                                deleteCount
                              }) => {
                                if (!variable) {
                                  return;
                                }
                                const { objRoot, variablePath } = variable;

                                const oldValue = p.get(objRoot, variablePath);
                                p.set(objRoot, variablePath, !oldValue);
                                return !oldValue;
                              })?.apply(null, [actionArgs]),
                            actionArgs
                          );
                        })()
                      : undefined;
                    if (
                      typeof $steps["updatePreviewPopup"] === "object" &&
                      typeof $steps["updatePreviewPopup"].then === "function"
                    ) {
                      $steps["updatePreviewPopup"] = await __wrapUserPromise(
                        {
                          type: "InteractionLoc",
                          actionName: "updateVariable",
                          interactionUuid: "feXYuzfq3LQ",
                          componentUuid: "-WLyt8cvAaz"
                        },
                        $steps["updatePreviewPopup"]
                      );
                    }
                    $steps["updateClickedImgUrl"] = true
                      ? (() => {
                          const actionArgs = {
                            variable: __wrapUserFunction(
                              {
                                type: "InteractionArgLoc",
                                actionName: "updateVariable",
                                interactionUuid: "YSFeaCO3XXv",
                                componentUuid: "-WLyt8cvAaz",
                                argName: "variable"
                              },
                              () => ({
                                objRoot: $state,
                                variablePath: ["clickedImgUrl"]
                              })
                            ),
                            operation: __wrapUserFunction(
                              {
                                type: "InteractionArgLoc",
                                actionName: "updateVariable",
                                interactionUuid: "YSFeaCO3XXv",
                                componentUuid: "-WLyt8cvAaz",
                                argName: "operation"
                              },
                              () => 0
                            ),
                            value: __wrapUserFunction(
                              {
                                type: "InteractionArgLoc",
                                actionName: "updateVariable",
                                interactionUuid: "YSFeaCO3XXv",
                                componentUuid: "-WLyt8cvAaz",
                                argName: "value"
                              },
                              () => currentItem.photoGallery
                            )
                          };
                          return __wrapUserFunction(
                            {
                              type: "InteractionLoc",
                              actionName: "updateVariable",
                              interactionUuid: "YSFeaCO3XXv",
                              componentUuid: "-WLyt8cvAaz"
                            },
                            () =>
                              (({
                                variable,
                                value,
                                startIndex,
                                deleteCount
                              }) => {
                                if (!variable) {
                                  return;
                                }
                                const { objRoot, variablePath } = variable;

                                p.set(objRoot, variablePath, value);
                                return value;
                              })?.apply(null, [actionArgs]),
                            actionArgs
                          );
                        })()
                      : undefined;
                    if (
                      typeof $steps["updateClickedImgUrl"] === "object" &&
                      typeof $steps["updateClickedImgUrl"].then === "function"
                    ) {
                      $steps["updateClickedImgUrl"] = await __wrapUserPromise(
                        {
                          type: "InteractionLoc",
                          actionName: "updateVariable",
                          interactionUuid: "YSFeaCO3XXv",
                          componentUuid: "-WLyt8cvAaz"
                        },
                        $steps["updateClickedImgUrl"]
                      );
                    }
                  }}
                  src={(() => {
                    try {
                      return currentItem.photoGallery;
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return "https://via.placeholder.com/150";
                      }
                      throw e;
                    }
                  })()}
                />
              </div>
            ))}
          </div>
          {(() => {
            try {
              return $ctx.graphCmsItem.audioUrl != null;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <Embed
              className={classNames("__wab_instance", sty.embedHtml__grXZk)}
              code={(() => {
                try {
                  return (
                    '<audio controls autoplay> <source src="' +
                    $ctx.graphCmsItem.audioUrl +
                    "\" type='audio/mpeg'></audio>"
                  );
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "<div>Audio Player</div>";
                  }
                  throw e;
                }
              })()}
            />
          ) : null}
        </p.Stack>
      </div>
      <div
        data-plasmic-name={"map"}
        data-plasmic-override={overrides.map}
        className={classNames(projectcss.all, sty.map)}
      >
        <p.Stack
          as={"div"}
          data-plasmic-name={"contentWrapper3"}
          data-plasmic-override={overrides.contentWrapper3}
          hasGap={true}
          className={classNames(projectcss.all, sty.contentWrapper3)}
        >
          {true ? (
            <p.Stack
              as={"div"}
              data-plasmic-name={"title3"}
              data-plasmic-override={overrides.title3}
              hasGap={true}
              className={classNames(projectcss.all, sty.title3)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__xRgX
                )}
              >
                {"Location"}
              </h2>
            </p.Stack>
          ) : null}
          <Iframe
            data-plasmic-name={"iframe"}
            data-plasmic-override={overrides.iframe}
            className={classNames("__wab_instance", sty.iframe)}
            preview={true}
            src={(() => {
              try {
                return $ctx.graphCmsItem.gmapsEmbed;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "https://www.example.com";
                }
                throw e;
              }
            })()}
          />

          <div className={classNames(projectcss.all, sty.freeBox__sBjBv)}>
            <Button
              className={classNames("__wab_instance", sty.button__ss2D)}
              color={"yellow" as const}
              link={(() => {
                try {
                  return (
                    "https://www.google.com/maps/place/" +
                    $ctx.graphCmsItem.eventMap.latitude +
                    "," +
                    $ctx.graphCmsItem.eventMap.longitude
                  );
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()}
            >
              {"Petunjuk Arah"}
            </Button>
          </div>
        </p.Stack>
      </div>
      <div
        data-plasmic-name={"footer"}
        data-plasmic-override={overrides.footer}
        className={classNames(projectcss.all, sty.footer)}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__capHd
          )}
        >
          {"Build with 💖 by Bentukcinta.com"}
        </div>
      </div>
      <WhatsappButton
        data-plasmic-name={"whatsappButton"}
        data-plasmic-override={overrides.whatsappButton}
        className={classNames("__wab_instance", sty.whatsappButton)}
        whatsapp2={
          <p.PlasmicLink
            data-plasmic-name={"link"}
            data-plasmic-override={overrides.link}
            className={classNames(projectcss.all, projectcss.a, sty.link)}
            component={Link}
            href={(() => {
              try {
                return (
                  "https://api.whatsapp.com/send?phone=" +
                  $ctx.graphCmsItem.phone1 +
                  "%20&text=Hi,%20ini%20pesan%20dari%20undangan%20online%20mu."
                );
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
            platform={"nextjs"}
          >
            <WhatsappSvgrepoComsvgIcon
              className={classNames(projectcss.all, sty.svg__zbTp8)}
              role={"img"}
            />
          </p.PlasmicLink>
        }
      />

      {true ? (
        <AntdModal
          data-plasmic-name={"modalTemplate3"}
          data-plasmic-override={overrides.modalTemplate3}
          className={classNames("__wab_instance", sty.modalTemplate3)}
          defaultStylesClassName={classNames(
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens
          )}
          footer={
            true ? (
              <div className={classNames(projectcss.all, sty.freeBox__en7Gl)}>
                <Button
                  className={classNames("__wab_instance", sty.button__pcgzo)}
                  color={"yellow" as const}
                  onClick={async event => {
                    const $steps = {};
                    $steps["updateModalOpen"] = true
                      ? (() => {
                          const actionArgs = {
                            variable: __wrapUserFunction(
                              {
                                type: "InteractionArgLoc",
                                actionName: "updateVariable",
                                interactionUuid: "vXe9dZ5sKgK",
                                componentUuid: "-WLyt8cvAaz",
                                argName: "variable"
                              },
                              () => ({
                                objRoot: $state,
                                variablePath: ["modalTemplate3", "open"]
                              })
                            ),
                            operation: __wrapUserFunction(
                              {
                                type: "InteractionArgLoc",
                                actionName: "updateVariable",
                                interactionUuid: "vXe9dZ5sKgK",
                                componentUuid: "-WLyt8cvAaz",
                                argName: "operation"
                              },
                              () => 4
                            )
                          };
                          return __wrapUserFunction(
                            {
                              type: "InteractionLoc",
                              actionName: "updateVariable",
                              interactionUuid: "vXe9dZ5sKgK",
                              componentUuid: "-WLyt8cvAaz"
                            },
                            () =>
                              (({
                                variable,
                                value,
                                startIndex,
                                deleteCount
                              }) => {
                                if (!variable) {
                                  return;
                                }
                                const { objRoot, variablePath } = variable;

                                const oldValue = p.get(objRoot, variablePath);
                                p.set(objRoot, variablePath, !oldValue);
                                return !oldValue;
                              })?.apply(null, [actionArgs]),
                            actionArgs
                          );
                        })()
                      : undefined;
                    if (
                      typeof $steps["updateModalOpen"] === "object" &&
                      typeof $steps["updateModalOpen"].then === "function"
                    ) {
                      $steps["updateModalOpen"] = await __wrapUserPromise(
                        {
                          type: "InteractionLoc",
                          actionName: "updateVariable",
                          interactionUuid: "vXe9dZ5sKgK",
                          componentUuid: "-WLyt8cvAaz"
                        },
                        $steps["updateModalOpen"]
                      );
                    }
                  }}
                >
                  {"Buka Undangan"}
                </Button>
              </div>
            ) : null
          }
          modalScopeClassName={sty["modalTemplate3__modal"]}
          onOpenChange={p.generateStateOnChangeProp($state, [
            "modalTemplate3",
            "open"
          ])}
          open={p.generateStateValueProp($state, ["modalTemplate3", "open"])}
          title={"BentukCinta"}
        >
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__vsIrb)}
          >
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__bOCiG)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__wlad5
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return $ctx.graphCmsItem.title;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "Jonh & Merry";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__mcTdi)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"64px" as const}
                  loading={"lazy" as const}
                  src={{
                    src: "/plasmic/bentuk_cintav_2/images/daunimagepng.png",
                    fullWidth: 240,
                    fullHeight: 93,
                    aspectRatio: undefined
                  }}
                />
              </div>
            ) : null}
            {(() => {
              try {
                return $ctx.query.to != null;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return false;
                }
                throw e;
              }
            })() ? (
              <div className={classNames(projectcss.all, sty.freeBox__vkc9J)}>
                {true ? (
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qnTn4
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $ctx.query.to;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "Puja";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                ) : null}
              </div>
            ) : null}
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__yfBV)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"part1"}
                data-plasmic-override={overrides.part1}
                hasGap={true}
                className={classNames(projectcss.all, sty.part1)}
              >
                <WashingHandsSvgrepoComsvgIcon
                  className={classNames(projectcss.all, sty.svg__wX75I)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gFfa4
                  )}
                >
                  {"Membersihkan Tangan"}
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                data-plasmic-name={"part12"}
                data-plasmic-override={overrides.part12}
                hasGap={true}
                className={classNames(projectcss.all, sty.part12)}
              >
                <Mask2SvgrepoComsvgIcon
                  className={classNames(projectcss.all, sty.svg__rj1X)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__b1Yo6
                  )}
                >
                  {"Memakai Masker"}
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                data-plasmic-name={"part13"}
                data-plasmic-override={overrides.part13}
                hasGap={true}
                className={classNames(projectcss.all, sty.part13)}
              >
                <SocialDistancingSvgrepoComsvgIcon
                  className={classNames(projectcss.all, sty.svg___746M)}
                  role={"img"}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__aAaAb
                  )}
                >
                  {"Menjaga Jarak"}
                </div>
              </p.Stack>
            </p.Stack>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__htQwc
              )}
            >
              {
                "Tanpa mengurangi rasa hormat, dikarenakan situasi yang sedang terjadi ditengah Pandemi Covid-19 ini kami memohon maaf karena acara akan diselenggarakan sesuai peraturan dan himbauan pemerintah."
              }
            </div>
          </p.Stack>
        </AntdModal>
      ) : null}
      {(() => {
        try {
          return $state.previewPopup;
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return true;
          }
          throw e;
        }
      })() ? (
        <ImagePreview
          data-plasmic-name={"imagePreview"}
          data-plasmic-override={overrides.imagePreview}
          className={classNames("__wab_instance", sty.imagePreview)}
          slot={
            <CloseCircleSvgrepoComsvgIcon
              className={classNames(projectcss.all, sty.svg__aju7Z)}
              onClick={async event => {
                const $steps = {};
                $steps["updatePreviewPopup"] = true
                  ? (() => {
                      const actionArgs = {
                        variable: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "BT3Y0UW3JJ9",
                            componentUuid: "-WLyt8cvAaz",
                            argName: "variable"
                          },
                          () => ({
                            objRoot: $state,
                            variablePath: ["previewPopup"]
                          })
                        ),
                        operation: __wrapUserFunction(
                          {
                            type: "InteractionArgLoc",
                            actionName: "updateVariable",
                            interactionUuid: "BT3Y0UW3JJ9",
                            componentUuid: "-WLyt8cvAaz",
                            argName: "operation"
                          },
                          () => 4
                        )
                      };
                      return __wrapUserFunction(
                        {
                          type: "InteractionLoc",
                          actionName: "updateVariable",
                          interactionUuid: "BT3Y0UW3JJ9",
                          componentUuid: "-WLyt8cvAaz"
                        },
                        () =>
                          (({ variable, value, startIndex, deleteCount }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            const oldValue = p.get(objRoot, variablePath);
                            p.set(objRoot, variablePath, !oldValue);
                            return !oldValue;
                          })?.apply(null, [actionArgs]),
                        actionArgs
                      );
                    })()
                  : undefined;
                if (
                  typeof $steps["updatePreviewPopup"] === "object" &&
                  typeof $steps["updatePreviewPopup"].then === "function"
                ) {
                  $steps["updatePreviewPopup"] = await __wrapUserPromise(
                    {
                      type: "InteractionLoc",
                      actionName: "updateVariable",
                      interactionUuid: "BT3Y0UW3JJ9",
                      componentUuid: "-WLyt8cvAaz"
                    },
                    $steps["updatePreviewPopup"]
                  );
                }
              }}
              role={"img"}
            />
          }
        >
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img___3Qx8P)}
            displayHeight={"auto" as const}
            displayMaxHeight={"100%" as const}
            displayMaxWidth={"100%" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={"auto" as const}
            loading={"lazy" as const}
            src={(() => {
              try {
                return $state.clickedImgUrl;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()}
          />
        </ImagePreview>
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "pageMetadataOverride",
    "hero",
    "slider",
    "desc",
    "details",
    "contentWrapper",
    "title",
    "pengantinDetails",
    "man",
    "girl",
    "acaraDetails",
    "dateTime",
    "title5",
    "gallery",
    "contentWrapper2",
    "title2",
    "youTube",
    "map",
    "contentWrapper3",
    "title3",
    "iframe",
    "footer",
    "whatsappButton",
    "link",
    "modalTemplate3",
    "part1",
    "part12",
    "part13",
    "imagePreview"
  ],
  pageMetadataOverride: ["pageMetadataOverride"],
  hero: ["hero", "slider", "desc"],
  slider: ["slider"],
  desc: ["desc"],
  details: [
    "details",
    "contentWrapper",
    "title",
    "pengantinDetails",
    "man",
    "girl",
    "acaraDetails",
    "dateTime",
    "title5"
  ],
  contentWrapper: [
    "contentWrapper",
    "title",
    "pengantinDetails",
    "man",
    "girl",
    "acaraDetails",
    "dateTime",
    "title5"
  ],
  title: ["title"],
  pengantinDetails: ["pengantinDetails", "man", "girl"],
  man: ["man"],
  girl: ["girl"],
  acaraDetails: ["acaraDetails", "dateTime"],
  dateTime: ["dateTime"],
  title5: ["title5"],
  gallery: ["gallery", "contentWrapper2", "title2", "youTube"],
  contentWrapper2: ["contentWrapper2", "title2", "youTube"],
  title2: ["title2"],
  youTube: ["youTube"],
  map: ["map", "contentWrapper3", "title3", "iframe"],
  contentWrapper3: ["contentWrapper3", "title3", "iframe"],
  title3: ["title3"],
  iframe: ["iframe"],
  footer: ["footer"],
  whatsappButton: ["whatsappButton", "link"],
  link: ["link"],
  modalTemplate3: ["modalTemplate3", "part1", "part12", "part13"],
  part1: ["part1"],
  part12: ["part12"],
  part13: ["part13"],
  imagePreview: ["imagePreview"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageMetadataOverride: typeof PlasmicHead;
  hero: "div";
  slider: typeof Slider;
  desc: "div";
  details: "div";
  contentWrapper: "div";
  title: "div";
  pengantinDetails: "div";
  man: "div";
  girl: "div";
  acaraDetails: "div";
  dateTime: "div";
  title5: "div";
  gallery: "div";
  contentWrapper2: "div";
  title2: "div";
  youTube: typeof YouTube;
  map: "div";
  contentWrapper3: "div";
  title3: "div";
  iframe: typeof Iframe;
  footer: "div";
  whatsappButton: typeof WhatsappButton;
  link: "a";
  modalTemplate3: typeof AntdModal;
  part1: "div";
  part12: "div";
  part13: "div";
  imagePreview: typeof ImagePreview;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTemplate3__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTemplate3__VariantsArgs;
    args?: PlasmicTemplate3__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTemplate3__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicTemplate3__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTemplate3__ArgProps,
          internalVariantPropNames: PlasmicTemplate3__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTemplate3__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTemplate3";
  } else {
    func.displayName = `PlasmicTemplate3.${nodeName}`;
  }
  return func;
}

export const PlasmicTemplate3 = Object.assign(
  // Top-level PlasmicTemplate3 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    pageMetadataOverride: makeNodeComponent("pageMetadataOverride"),
    hero: makeNodeComponent("hero"),
    slider: makeNodeComponent("slider"),
    desc: makeNodeComponent("desc"),
    details: makeNodeComponent("details"),
    contentWrapper: makeNodeComponent("contentWrapper"),
    title: makeNodeComponent("title"),
    pengantinDetails: makeNodeComponent("pengantinDetails"),
    man: makeNodeComponent("man"),
    girl: makeNodeComponent("girl"),
    acaraDetails: makeNodeComponent("acaraDetails"),
    dateTime: makeNodeComponent("dateTime"),
    title5: makeNodeComponent("title5"),
    gallery: makeNodeComponent("gallery"),
    contentWrapper2: makeNodeComponent("contentWrapper2"),
    title2: makeNodeComponent("title2"),
    youTube: makeNodeComponent("youTube"),
    map: makeNodeComponent("map"),
    contentWrapper3: makeNodeComponent("contentWrapper3"),
    title3: makeNodeComponent("title3"),
    iframe: makeNodeComponent("iframe"),
    footer: makeNodeComponent("footer"),
    whatsappButton: makeNodeComponent("whatsappButton"),
    link: makeNodeComponent("link"),
    modalTemplate3: makeNodeComponent("modalTemplate3"),
    part1: makeNodeComponent("part1"),
    part12: makeNodeComponent("part12"),
    part13: makeNodeComponent("part13"),
    imagePreview: makeNodeComponent("imagePreview"),

    // Metadata about props expected for PlasmicTemplate3
    internalVariantProps: PlasmicTemplate3__VariantProps,
    internalArgProps: PlasmicTemplate3__ArgProps
  }
);

export default PlasmicTemplate3;
/* prettier-ignore-end */
