// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 62fk78rY9xoShC3bnaKgA9

import * as React from "react";
import { hasVariant, ensureGlobalVariants } from "@plasmicapp/react-web";
import { GraphCMSCredentialsProvider } from "@plasmicpkgs/plasmic-graphcms"; // plasmic-import: hNB_eBOLhAQ/codeComponent

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  graphCMSCredentialsProviderProps?: Partial<
    Omit<React.ComponentProps<typeof GraphCMSCredentialsProvider>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, graphCMSCredentialsProviderProps } = props;

  return (
    <GraphCMSCredentialsProvider
      {...graphCMSCredentialsProviderProps}
      apiUrl={
        graphCMSCredentialsProviderProps &&
        "apiUrl" in graphCMSCredentialsProviderProps
          ? graphCMSCredentialsProviderProps.apiUrl!
          : ("https://api-ap-southeast-2.hygraph.com/v2/cl82rkf9k2ort01t37ifdad65/master" as const)
      }
      authToken={
        graphCMSCredentialsProviderProps &&
        "authToken" in graphCMSCredentialsProviderProps
          ? graphCMSCredentialsProviderProps.authToken!
          : ("eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImdjbXMtbWFpbi1wcm9kdWN0aW9uIn0.eyJ2ZXJzaW9uIjozLCJpYXQiOjE2NjMyMzgyMTYsImF1ZCI6WyJodHRwczovL2FwaS1hcC1zb3V0aGVhc3QtMi5oeWdyYXBoLmNvbS92Mi9jbDgycmtmOWsyb3J0MDF0MzdpZmRhZDY1L21hc3RlciIsIm1hbmFnZW1lbnQtbmV4dC5ncmFwaGNtcy5jb20iXSwiaXNzIjoiaHR0cHM6Ly9tYW5hZ2VtZW50LmdyYXBoY21zLmNvbS8iLCJzdWIiOiJmZGQ2MWYwNS0wNTVhLTRmYzUtYjc4MC02Yjc3MmM1YjE1MTciLCJqdGkiOiJjbDgyeDM5Y2cwOHR3MDF0MzkyYWZndDFxIn0.xX5MTdp4KTeR8n9WpAao3aElZOqnR530tUIh45EffqYmQD8ElomEMwJq9n-RtvoDy25nueyDU7_nsySLjRV-xiCD4WYDVETcnvOqNu_l3QlfMxFvIvMVQj7Qm9z9T56D_humi-VMAIwKHx4jPfuhenD1np5l1nkw4dfU-GdIU2PRK5wETddBqykzaCoMp8yTtawDMG2YgIhgPN4iqiesRf73JYPy9cGUHJXezrGnh6t3hOElNhDpLh6vWXgKrjBKxpbf6wI4HBspPt0ElJ268zFsMEoh0UlkktXiPCgi7uEljxUA1TwomMSEpG-wnG1v5yj-as0DJ09TDFrllUpfWpdRKGRpnAE7lsgSAXWyp3AUVxsdCMnpP7A0UENk9EiSWVx8aTYPX-CFw_avlZCTmt6mrNZIOByzKk7XnOYcA3LUsCVfCrthndt3UIg8vlE2xCWyH3eLIi4DjGGCD2KW8-9fNFsqZBt6t5t-y1ZTXgdL4kuN_dYUT7Wlwe0GSPmPZx3e8C264Cga-Lu66zSJV8ikliW3najMlkzDcXyY2pSeBNLwkbDFVd1RCSe_J6M4sd0f0ftqUp37l-m8XZxQ06bFRULcMrikruG9cynalbiZWVrzXCNx36HOWra1MKR-ioaKli0iBTN2tE94IbRnHFyRnQYKgHiQkT3g2rvnMyQ" as const)
      }
    >
      {children}
    </GraphCMSCredentialsProvider>
  );
}
